import * as dependency_1 from "./gen/types"

export const definitions = {
    image: {
        create: {
            path: "/maarpc.Image/create",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.HandleResponse,
        },
        destroy: {
            path: "/maarpc.Image/destroy",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        is_empty: {
            path: "/maarpc.Image/is_empty",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BoolResponse,
        },
        clear: {
            path: "/maarpc.Image/clear",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        info: {
            path: "/maarpc.Image/info",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.ImageInfoResponse,
        },
        encoded: {
            path: "/maarpc.Image/encoded",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BufferResponse,
        },
        set_encoded: {
            path: "/maarpc.Image/set_encoded",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleBufferRequest,
            response: dependency_1.BoolResponse,
        }
    },

    config: {
        init: {
            path: "/maarpc.Config/init",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.EmptyResponse,
        },
        uninit: {
            path: "/maarpc.Config/uninit",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.EmptyResponse,
        }
    },

    controller: {
        create_adb: {
            path: "/maarpc.Controller/create_adb",
            requestStream: false,
            responseStream: false,
            request: dependency_1.AdbControllerRequest,
            response: dependency_1.HandleResponse,
        },
        destroy: {
            path: "/maarpc.Controller/destroy",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        create_custom: {
            path: "/maarpc.Controller/create_custom",
            requestStream: true,
            responseStream: true,
            request: dependency_1.CustomControllerRequest,
            response: dependency_1.CustomControllerResponse,
        },
        set_option: {
            path: "/maarpc.Controller/set_option",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerSetOptionRequest,
            response: dependency_1.EmptyResponse,
        },
        post_connection: {
            path: "/maarpc.Controller/post_connection",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.IIdResponse,
        },
        post_click: {
            path: "/maarpc.Controller/post_click",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostClickRequest,
            response: dependency_1.IIdResponse,
        },
        post_swipe: {
            path: "/maarpc.Controller/post_swipe",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostSwipeRequest,
            response: dependency_1.IIdResponse,
        },
        post_press_key: {
            path: "/maarpc.Controller/post_press_key",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostKeyRequest,
            response: dependency_1.IIdResponse,
        },
        post_touch_down: {
            path: "/maarpc.Controller/post_touch_down",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostTouchRequest,
            response: dependency_1.IIdResponse,
        },
        post_touch_move: {
            path: "/maarpc.Controller/post_touch_move",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostTouchRequest,
            response: dependency_1.IIdResponse,
        },
        post_touch_up: {
            path: "/maarpc.Controller/post_touch_up",
            requestStream: false,
            responseStream: false,
            request: dependency_1.ControllerPostTouchRequest,
            response: dependency_1.IIdResponse,
        },
        post_screencap: {
            path: "/maarpc.Controller/post_screencap",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.IIdResponse,
        },
        status: {
            path: "/maarpc.Controller/status",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        wait: {
            path: "/maarpc.Controller/wait",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        connected: {
            path: "/maarpc.Controller/connected",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BoolResponse,
        },
        image: {
            path: "/maarpc.Controller/image",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleHandleRequest,
            response: dependency_1.EmptyResponse,
        },
        uuid: {
            path: "/maarpc.Controller/uuid",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.StringResponse,
        }
    },

    device: {
        find: {
            path: "/maarpc.Device/find",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.DeviceInfosResponse,
        },
        find_with_adb: {
            path: "/maarpc.Device/find_with_adb",
            requestStream: false,
            responseStream: false,
            request: dependency_1.StringRequest,
            response: dependency_1.DeviceInfosResponse,
        }
    },

    instance: {
        create: {
            path: "/maarpc.Instance/create",
            requestStream: false,
            responseStream: false,
            request: dependency_1.IdRequest,
            response: dependency_1.HandleResponse,
        },
        destroy: {
            path: "/maarpc.Instance/destroy",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        register_custom_recognizer: {
            path: "/maarpc.Instance/register_custom_recognizer",
            requestStream: true,
            responseStream: true,
            request: dependency_1.CustomRecognizerRequest,
            response: dependency_1.CustomRecognizerResponse,
        },
        unregister_custom_recognizer: {
            path: "/maarpc.Instance/unregister_custom_recognizer",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleStringRequest,
            response: dependency_1.EmptyResponse,
        },
        clear_custom_recognizer: {
            path: "/maarpc.Instance/clear_custom_recognizer",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        register_custom_action: {
            path: "/maarpc.Instance/register_custom_action",
            requestStream: true,
            responseStream: true,
            request: dependency_1.CustomActionRequest,
            response: dependency_1.CustomActionResponse,
        },
        unregister_custom_action: {
            path: "/maarpc.Instance/unregister_custom_action",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleStringRequest,
            response: dependency_1.EmptyResponse,
        },
        clear_custom_action: {
            path: "/maarpc.Instance/clear_custom_action",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        bind_resource: {
            path: "/maarpc.Instance/bind_resource",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleHandleRequest,
            response: dependency_1.EmptyResponse,
        },
        bind_controller: {
            path: "/maarpc.Instance/bind_controller",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleHandleRequest,
            response: dependency_1.EmptyResponse,
        },
        inited: {
            path: "/maarpc.Instance/inited",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BoolResponse,
        },
        post_task: {
            path: "/maarpc.Instance/post_task",
            requestStream: false,
            responseStream: false,
            request: dependency_1.InstancePostTaskRequest,
            response: dependency_1.IIdResponse,
        },
        set_task_param: {
            path: "/maarpc.Instance/set_task_param",
            requestStream: false,
            responseStream: false,
            request: dependency_1.InstanceSetTaskParamRequest,
            response: dependency_1.EmptyResponse,
        },
        status: {
            path: "/maarpc.Instance/status",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        wait: {
            path: "/maarpc.Instance/wait",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        all_finished: {
            path: "/maarpc.Instance/all_finished",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BoolResponse,
        },
        stop: {
            path: "/maarpc.Instance/stop",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        resource: {
            path: "/maarpc.Instance/resource",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.HandleRequest,
        },
        controller: {
            path: "/maarpc.Instance/controller",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.HandleRequest,
        }
    },

    resource: {
        create: {
            path: "/maarpc.Resource/create",
            requestStream: false,
            responseStream: false,
            request: dependency_1.IdRequest,
            response: dependency_1.HandleResponse,
        },
        destroy: {
            path: "/maarpc.Resource/destroy",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.EmptyResponse,
        },
        post_path: {
            path: "/maarpc.Resource/post_path",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleStringRequest,
            response: dependency_1.IIdResponse,
        },
        status: {
            path: "/maarpc.Resource/status",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        wait: {
            path: "/maarpc.Resource/wait",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleIIdRequest,
            response: dependency_1.StatusResponse,
        },
        loaded: {
            path: "/maarpc.Resource/loaded",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.BoolResponse,
        },
        hash: {
            path: "/maarpc.Resource/hash",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleRequest,
            response: dependency_1.StringResponse,
        }
    },

    synccontext: {
        run_task: {
            path: "/maarpc.SyncContext/run_task",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextRunTaskRequest,
            response: dependency_1.EmptyResponse,
        },
        run_recognizer: {
            path: "/maarpc.SyncContext/run_recognizer",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextRunRecognizerRequest,
            response: dependency_1.SyncContextRunRecognizerResponse,
        },
        run_action: {
            path: "/maarpc.SyncContext/run_action",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextRunActionRequest,
            response: dependency_1.EmptyResponse,
        },
        click: {
            path: "/maarpc.SyncContext/click",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextClickRequest,
            response: dependency_1.EmptyRequest,
        },
        swipe: {
            path: "/maarpc.SyncContext/swipe",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextSwipeRequest,
            response: dependency_1.EmptyRequest,
        },
        key: {
            path: "/maarpc.SyncContext/key",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextKeyRequest,
            response: dependency_1.EmptyRequest,
        },
        touch_down: {
            path: "/maarpc.SyncContext/touch_down",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextTouchRequest,
            response: dependency_1.EmptyRequest,
        },
        touch_move: {
            path: "/maarpc.SyncContext/touch_move",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextTouchRequest,
            response: dependency_1.EmptyRequest,
        },
        touch_up: {
            path: "/maarpc.SyncContext/touch_up",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextTouchRequest,
            response: dependency_1.EmptyRequest,
        },
        screencap: {
            path: "/maarpc.SyncContext/screencap",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SyncContextScreencapRequest,
            response: dependency_1.EmptyResponse,
        },
        task_result: {
            path: "/maarpc.SyncContext/task_result",
            requestStream: false,
            responseStream: false,
            request: dependency_1.HandleStringRequest,
            response: dependency_1.StringResponse,
        }
    },

    utility: {
        version: {
            path: "/maarpc.Utility/version",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.StringResponse,
        },
        set_global_option: {
            path: "/maarpc.Utility/set_global_option",
            requestStream: false,
            responseStream: false,
            request: dependency_1.SetGlobalOptionRequest,
            response: dependency_1.EmptyResponse,
        },
        acquire_id: {
            path: "/maarpc.Utility/acquire_id",
            requestStream: false,
            responseStream: false,
            request: dependency_1.EmptyRequest,
            response: dependency_1.IdResponse,
        },
        register_callback: {
            path: "/maarpc.Utility/register_callback",
            requestStream: false,
            responseStream: true,
            request: dependency_1.IdRequest,
            response: dependency_1.Callback,
        },
        unregister_callback: {
            path: "/maarpc.Utility/unregister_callback",
            requestStream: false,
            responseStream: false,
            request: dependency_1.IdRequest,
            response: dependency_1.EmptyResponse,
        }
    },

} as const